version: 1619416789282
language: cn
aomori_widgets:
  - category
  - tag
  - joinuser

#me
me_avatar: /images/avatar.jpg
me_name: blueberry

#joinuser
joinuser_list:
  - 
    name: blueberry
    logo: /images/avatar_blueberry.jpg
    url: https://github.com/JuneBlueberry
  - 
    name: may
    logo: /images/avatar_may.jpg
    # url: https://github.com/JuneBlueberry